# Generated by Django 2.2.2 on 2019-07-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novarock_voting_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ('choice_id', 'name'), 'verbose_name': 'Band', 'verbose_name_plural': 'Bands'},
        ),
        migrations.AlterModelOptions(
            name='proxy',
            options={'ordering': ('url',), 'verbose_name': 'Proxy', 'verbose_name_plural': 'Proxies'},
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bands', models.ManyToManyField(to='novarock_voting_bot.Band')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novarock_voting_bot.Proxy')),
            ],
        ),
    ]
