# Generated by Django 2.2.2 on 2019-07-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novarock_voting_bot', '0002_auto_20190701_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='response_code',
            field=models.IntegerField(default=200),
        ),
    ]
