# Generated by Django 2.2.1 on 2019-05-29 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('wish_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(choices=[('EUR', '€'), ('DOL', '$')], max_length=3)),
                ('alarm_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_page', models.CharField(choices=[('kotte-zeller.de', 'https://www.kotte-zeller.de'), ('softairstore.de', 'https://www.softairstore.de'), ('shoot-club.de', 'https://www.shoot-club.de'), ('softairwelt.de', 'https://www.softairwelt.de'), ('airsoft2go.de', 'https://airsoft2go.de')], max_length=64)),
                ('suffix_url', models.CharField(max_length=256)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_control.Product')),
            ],
            options={
                'verbose_name': 'Price Control Page',
                'verbose_name_plural': 'Price Control Pages',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_control.Page')),
            ],
            options={
                'verbose_name': 'Auditlog',
                'verbose_name_plural': 'Auditlogs',
            },
        ),
    ]
