# Generated by Django 2.2.1 on 2019-05-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('img', models.ImageField(upload_to='')),
                ('wish_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(choices=[('EUR', '€'), ('DOL', '$')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PriceControlPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_page', models.CharField(choices=[('kotte-zeller.de', 'https://www.kotte-zeller.de/')], max_length=64)),
                ('suffix_url', models.CharField(max_length=256)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_control.ProductPriceControl')),
            ],
        ),
        migrations.CreateModel(
            name='AuditControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_control_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_control.PriceControlPage')),
            ],
        ),
    ]
