# Generated by Django 2.2.1 on 2019-05-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditcontrol',
            options={'verbose_name': 'Audit', 'verbose_name_plural': 'Audit'},
        ),
        migrations.AlterModelOptions(
            name='pricecontrolpage',
            options={'verbose_name': 'Price Control Page', 'verbose_name_plural': 'Price Control Pages'},
        ),
        migrations.AlterModelOptions(
            name='productpricecontrol',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='productpricecontrol',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
