# Generated by Django 2.2.1 on 2019-05-29 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_control', '0002_auto_20190529_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='price_control.Page'),
        ),
    ]
