# Generated by Django 2.2.1 on 2019-05-18 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price_control', '0002_auto_20190518_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcontrol',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricecontrolpage',
            name='web_page',
            field=models.CharField(choices=[('kotte-zeller.de', 'https://www.kotte-zeller.de')], max_length=64),
        ),
    ]
