# Generated by Django 2.2.1 on 2019-06-03 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_control', '0003_auto_20190529_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Auditlog', 'verbose_name_plural': 'Auditlogs'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('product', 'web_page'), 'verbose_name': 'Price Control Page', 'verbose_name_plural': 'Price Control Pages'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('alarm_user', 'name'), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
