# Generated by Django 2.2.2 on 2019-06-22 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoMaintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Repository Maintainer',
                'verbose_name_plural': 'Repository Maintainers',
                'ordering': ('repo_id',),
            },
        ),
        migrations.CreateModel(
            name='OdooProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=256)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odoo_product', to='odoo_sales_check.RepoMaintainer')),
            ],
            options={
                'verbose_name': 'Odoo Product',
                'verbose_name_plural': 'Odoo Products',
                'ordering': ('repo',),
            },
        ),
        migrations.CreateModel(
            name='AuditSalesCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_sales_check', to='odoo_sales_check.OdooProduct')),
            ],
            options={
                'verbose_name': 'Audit Salescheck',
                'verbose_name_plural': 'Audit Saleschecks',
                'ordering': ('created_at', 'product'),
            },
        ),
    ]
