# Generated by Django 2.2.2 on 2019-07-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odoo_sales_check', '0002_repomaintainer_alarm_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditsalescheck',
            options={'ordering': ('-created_at', 'product'), 'verbose_name': 'Audit Salescheck', 'verbose_name_plural': 'Audit Saleschecks'},
        ),
    ]
